### ISSUE TITLE
Unsupported URL scheme

### ISSUE THREAD

**Issue by renzified** [matt-block/react-native-in-app-browser#110]
this does not support intent:// url scheme

**Comment by matei-radu** [comment]
Hi! This project is no longer under development, mainly because I haven't been working with React Native for a long time.

Like I wrote in the Readme, I recommend you have a look at [react-native-inappbrowser-reborn](https://github.com/proyecto26/react-native-inappbrowser) which has more features and is under active development.

**Comment by renzified** [comment]
Very much appreciated thanks and cheers
